name: Project Arduino Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare The Arduino Library
        run: |
          bash -x ./scripts/setup-project.sh github-action-upload

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iotc-mchp-avr-sdk
          path: ./iotc-mchp-avr-sdk
